# Generated by Django 4.2.3 on 2023-10-07 00:23

from django.db import migrations


DRONE_STATUSES = [
    {"text": "idle"},
    {"text": "delivering"},
    {"text": "owner"},
]


def populate(apps, schema_editor):
    DroneStatus = apps.get_model("api", "DroneStatus")

    for status in DRONE_STATUSES:
        DroneStatus(
            text=status["text"]
        ).save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_populate_DroneType'),
    ]

    operations = [
        migrations.RunPython(populate)
    ]
