# Generated by Django 4.2.3 on 2023-10-15 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_populate_OrderStatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerToken',
            fields=[
                ('token', models.CharField(max_length=128,
                 primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='api.customer')),
            ],
        ),
    ]
