# Generated by Django 4.2.3 on 2023-10-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_populate_OrderStatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='first_name',
            field=models.CharField(default='NO_FIRST_NAME', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='last_name',
            field=models.CharField(default='NO_LAST_NAME', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='owner',
            name='first_name',
            field=models.CharField(default='NO_FIRST_NAME', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='owner',
            name='last_name',
            field=models.CharField(default='NO_LAST_NAME', max_length=64),
            preserve_default=False,
        ),
    ]
