# Generated by Django 4.2.3 on 2023-11-08 18:11

from django.db import migrations
from django.contrib.auth.hashers import make_password


MANAGERS = [
    {
        "username": "manager01",
        "password": "password",
        "first_name": "Default",
        "last_name": "Manager"
    },
]


def populate(apps, schema_editor):
    Manager = apps.get_model("api", "Manager")
    for manager in MANAGERS:
        Manager(
            username=manager['username'],
            password_hash=make_password(manager['password']),
            first_name=manager['first_name'],
            last_name=manager['last_name'],
        ).save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_populate_TreatTypes'),
    ]

    operations = [
        migrations.RunPython(populate)
    ]
