# Generated by Django 4.2.3 on 2023-10-14 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_customer_first_name_customer_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='passwordHash',
            new_name='password_hash',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='passwordHash',
            new_name='password_hash',
        ),
    ]
