# Generated by Django 4.2.3 on 2023-11-16 02:19

from django.db import migrations
from django.contrib.auth.hashers import make_password


CUSTOMERS = [
    {
        "username": "customer01",
        "password": "password",
        "first_name": "Default",
        "last_name": "Customer",
        "addresses": [
            {
                "line_one": "1234 E. Champ Ave.",
                "line_two": "",
                "city": "Logan",
                "state": "UT",
                "zip_code": "84321"
            }
        ]
    }
]

OWNERS = [
    {
        "username": "owner01",
        "password": "password",
        "first_name": "Default",
        "last_name": "Owner",
        "drones": [
            {
                "name": "Drone01",
                "status": "idle",
                "drone_type": "light"
            },
            {
                "name": "Drone02",
                "status": "idle",
                "drone_type": "heavy"
            },
        ]
    },
]


def populate(apps, schema_editor):
    Customer = apps.get_model("api", "Customer")
    Address = apps.get_model("api", "Address")

    for c in CUSTOMERS:
        customer = Customer(
            username=c['username'],
            password_hash=make_password(c['password']),
            first_name=c['first_name'],
            last_name=c['last_name'],
        )
        customer.save()

        for a in c["addresses"]:
            address = Address(
                line_one=a["line_one"],
                line_two=a["line_two"],
                city=a["city"],
                state=a["state"],
                zip_code=a["zip_code"],
                customer=customer,
            )
            address.save()

    Owner = apps.get_model("api", "Owner")
    Drone = apps.get_model("api", "Drone")
    DroneStatus = apps.get_model("api", "DroneStatus")
    DroneType = apps.get_model("api", "DroneType")

    for o in OWNERS:
        owner = Owner(
            username=o['username'],
            password_hash=make_password(o['password']),
            first_name=o['first_name'],
            last_name=o['last_name'],
        )
        owner.save()

        for d in o["drones"]:
            drone = Drone(
                name=d["name"],
                status=DroneStatus.objects.get(text=d["status"]),
                drone_type=DroneType.objects.get(text=d["drone_type"]),
                owner=owner,
            )
            drone.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_populate_Managers'),
    ]

    operations = [
        migrations.RunPython(populate)
    ]
